image: oven/bun:alpine

# variables:
#   BUN_VERSION: "1.0.30"

stages:
  - setup
  - build
  - release

# Cache dependencies between jobs
cache:
  key:
    files:
      - bun.lockb
      - package.json
  paths:
    - node_modules/

install:
  stage: setup
  script:
    - bun --version
    - bun install --frozen-lockfile

build:
  stage: build
  needs:
    - install
  script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev
    - apk add nodejs npm
    - npm install -g node-gyp
    - bun run prebuild
    - bun run build
    - bun run build-ff
    - bun run package
    - bun run package-ff
  artifacts:
    paths:
      - build/chrome-mv3-prod.zip
      - build/firefox-mv2-prod.zip
    expire_in: 1 week

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
  when: on_success
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --description "Release $CI_COMMIT_TAG of the Passman Webextension v3" \
        --assets-link "{\"name\":\"chrome-mv3-prod.zip\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/chrome-mv3-prod.zip\"}" \
        --assets-link "{\"name\":\"firefox-mv2-prod.zip\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/firefox-mv2-prod.zip\"}"
